name: Update Doxygen Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Commit and Push Documentation
        uses: elstudio/actions-js-build@v1
        with:
          branch: gh-pages
          folder: docs/html/
